In [1]:
import pandas as pd

url = "https://data.bls.gov/cew/data/files/2024/csv/2024_annual_singlefile.zip"

qcew = pd.read_csv(
    url,
    compression="zip",
    low_memory=False
)

print(qcew.shape)
print(qcew.columns.tolist())
qcew.head()

(3664909, 38)
['area_fips', 'own_code', 'industry_code', 'agglvl_code', 'size_code', 'year', 'qtr', 'disclosure_code', 'annual_avg_estabs', 'annual_avg_emplvl', 'total_annual_wages', 'taxable_annual_wages', 'annual_contributions', 'annual_avg_wkly_wage', 'avg_annual_pay', 'lq_disclosure_code', 'lq_annual_avg_estabs', 'lq_annual_avg_emplvl', 'lq_total_annual_wages', 'lq_taxable_annual_wages', 'lq_annual_contributions', 'lq_annual_avg_wkly_wage', 'lq_avg_annual_pay', 'oty_disclosure_code', 'oty_annual_avg_estabs_chg', 'oty_annual_avg_estabs_pct_chg', 'oty_annual_avg_emplvl_chg', 'oty_annual_avg_emplvl_pct_chg', 'oty_total_annual_wages_chg', 'oty_total_annual_wages_pct_chg', 'oty_taxable_annual_wages_chg', 'oty_taxable_annual_wages_pct_chg', 'oty_annual_contributions_chg', 'oty_annual_contributions_pct_chg', 'oty_annual_avg_wkly_wage_chg', 'oty_annual_avg_wkly_wage_pct_chg', 'oty_avg_annual_pay_chg', 'oty_avg_annual_pay_pct_chg']

,area_fips,own_code,industry_code,agglvl_code,size_code,year,qtr,disclosure_code,annual_avg_estabs,annual_avg_emplvl,...,oty_total_annual_wages_chg,oty_total_annual_wages_pct_chg,oty_taxable_annual_wages_chg,oty_taxable_annual_wages_pct_chg,oty_annual_contributions_chg,oty_annual_contributions_pct_chg,oty_annual_avg_wkly_wage_chg,oty_annual_avg_wkly_wage_pct_chg,oty_avg_annual_pay_chg,oty_avg_annual_pay_pct_chg
0,01000,0,10,50,0,2024,A,NaN,160887,2105674,...,6545101020,5.3,-83727320,-0.5,-23329961,-20.7,43,3.7,2260,3.8
1,01000,1,10,51,0,2024,A,NaN,1269,58132,...,317386867,5.7,0,0.0,0,0.0,65,3.5,3417,3.5
2,01000,1,101,52,0,2024,A,NaN,1,1,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
3,01000,1,1013,53,0,2024,A,NaN,1,1,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
4,01000,1,102,52,0,2024,A,NaN,1268,58131,...,317328764,5.7,0,0.0,0,0.0,65,3.5,3417,3.5

In [3]:
print(qcew['agglvl_code'].value_counts().sort_index())

print("\nOwnership codes:")
print(qcew['own_code'].value_counts().sort_index())

agglvl_code
10          1
11          4
12          8
13         47
14         77
15        299
16        766
17       1417
18       1905
30        184
40        393
41       1571
42        786
43       4226
44       7760
45      32004
46      96526
47     185736
48     244498
50         53
51        211
52        386
53       1943
54       3014
55       8957
56      21985
57      42547
58      57658
70       3275
71      13007
72      19167
73      69904
74     102637
75     271696
76     555927
77     875986
78    1037748
80        542
91          1
92          1
93          1
94          1
95          1
96         53
Name: count, dtype: int64

Ownership codes:
own_code
0       4451
1     119932
2     149693
3     228220
5    3162558
8         54
9          1
Name: count, dtype: int64

In [4]:
print(qcew[['area_fips', 'agglvl_code', 'industry_code', 'own_code']].head(30))

   area_fips  agglvl_code industry_code  own_code
0      01000           50            10         0
1      01000           51            10         1
2      01000           52           101         1
3      01000           53          1013         1
4      01000           52           102         1
5      01000           53          1021         1
6      01000           53          1022         1
7      01000           53          1023         1
8      01000           53          1024         1
9      01000           53          1025         1
10     01000           53          1026         1
11     01000           53          1027         1
12     01000           53          1028         1
13     01000           54            22         1
14     01000           55           221         1
15     01000           56          2211         1
16     01000           57         22111         1
17     01000           58        221111         1
18     01000           58        221112         1
19     01000           58        221113         1
20     01000           57         22112         1
21     01000           58        221121         1
22     01000           58        221122         1
23     01000           54         31-33         1
24     01000           55           323         1
25     01000           56          3231         1
26     01000           57         32311         1
27     01000           58        323111         1
28     01000           58        323117         1
29     01000           54         44-45         1

In [5]:
state_total = qcew[
    (qcew['area_fips'].str.endswith('000')) &
    (qcew['own_code'] == 0)
]

print(state_total['agglvl_code'].value_counts().sort_index())

print(
    state_total[
        ['area_fips', 'agglvl_code', 'industry_code',
         'annual_avg_emplvl', 'annual_avg_wkly_wage']
    ].head(100).to_string(index=False)
)

agglvl_code
10     1
50    53
Name: count, dtype: int64
area_fips  agglvl_code industry_code  annual_avg_emplvl  annual_avg_wkly_wage
    01000           50            10            2105674                  1193
    02000           50            10             329164                  1382
    04000           50            10            3222450                  1354
    05000           50            10            1295577                  1123
    06000           50            10           18183696                  1772
    08000           50            10            2897901                  1544
    09000           50            10            1683378                  1683
    10000           50            10             477336                  1392
    11000           50            10             759666                  2365
    12000           50            10            9836491                  1336
    13000           50            10            4862001                  1358
    15000           50            10             639801                  1295
    16000           50            10             858504                  1146
    17000           50            10            6043357                  1486
    18000           50            10            3179542                  1206
    19000           50            10            1562561                  1180
    20000           50            10            1429358                  1169
    21000           50            10            1988347                  1162
    22000           50            10            1920359                  1179
    23000           50            10             648874                  1216
    24000           50            10            2768546                  1518
    25000           50            10            3644805                  1848
    26000           50            10            4407319                  1313
    27000           50            10            2932411                  1427
    28000           50            10            1167716                   980
    29000           50            10            2898179                  1230
    30000           50            10             512774                  1155
    31000           50            10            1018759                  1174
    32000           50            10            1551426                  1290
    33000           50            10             687990                  1489
    34000           50            10            4252229                  1603
    35000           50            10             869987                  1171
    36000           50            10            9705821                  1829
    37000           50            10            4901211                  1322
    38000           50            10             428692                  1263
    39000           50            10            5520656                  1267
    40000           50            10            1692477                  1129
    41000           50            10            1994161                  1371
    42000           50            10            6019836                  1379
    44000           50            10             495179                  1313
    45000           50            10            2284611                  1173
    46000           50            10             458558                  1121
    47000           50            10            3270771                  1297
    48000           50            10           13936364                  1450
    49000           50            10            1714013                  1286
    50000           50            10             309138                  1240
    51000           50            10            4106139                  1494
    53000           50            10            3594439                  1827
    54000           50            10             695658                  1121
    55000           50            10            2944347                  1220
    56000           50            10             282194                  1185
    72000           50            10             947908                   679
    78000           50            10              35639                  1009
    US000           10            10          154990441                  1454

In [6]:
sector_2024 = qcew[
    (qcew['agglvl_code'] == 54) &
    (qcew['own_code'].isin([1, 2, 3, 5]))
].copy()

print("Shape:", sector_2024.shape)

print(
    sector_2024[
        [
            'area_fips',
            'own_code',
            'industry_code',
            'annual_avg_emplvl',
            'total_annual_wages',
            'annual_avg_wkly_wage'
        ]
    ].head(30).to_string(index=False)
)

Shape: (3014, 38)
area_fips  own_code industry_code  annual_avg_emplvl  total_annual_wages  annual_avg_wkly_wage
    01000         1            22               1515           269049064                  3414
    01000         1         31-33                  1               58103                  1490
    01000         1         44-45               1145            25673971                   431
    01000         1         48-49               9211           619797147                  1294
    01000         1            51                 10              380506                   744
    01000         1            52                155            17142085                  2122
    01000         1            54               1895           173908785                  1765
    01000         1            56                  9              326246                   666
    01000         1            61                268            16069689                  1155
    01000         1            62               7393           683085358                  1777
    01000         1            71                309            12097152                   753
    01000         1            72                276             9867121                   688
    01000         1            81                591            93727214                  3052
    01000         1            92              35355          3934885714                  2140
    01000         2         44-45                663            26505977                   769
    01000         2         48-49                581            44121631                  1459
    01000         2            51                 84             6536629                  1502
    01000         2            52                 80             7410303                  1779
    01000         2            61              48857          3418940726                  1346
    01000         2            62              24331          1779349159                  1406
    01000         2            71                236            11718764                   955
    01000         2            72                 36              646779                   346
    01000         2            81                 53             2880010                  1047
    01000         2            92              30565          1969482136                  1239
    01000         3            22               7596           532117478                  1347
    01000         3            23                  0                   0                     0
    01000         3         31-33                  0                   0                     0
    01000         3            42                  0                   0                     0
    01000         3         44-45                  0                   0                     0
    01000         3         48-49               5081           174471597                   660

In [7]:
# Aggregate ownership sectors into State × Industry
state_industry_2024 = (
    sector_2024
    .groupby(
        ['area_fips', 'year', 'industry_code'],
        as_index=False
    )
    .agg(
        establishments=('annual_avg_estabs', 'sum'),
        employment=('annual_avg_emplvl', 'sum'),
        total_wages=('total_annual_wages', 'sum')
    )
)

# Recalculate annual pay from totals
state_industry_2024['avg_annual_pay'] = (
    state_industry_2024['total_wages']
    / state_industry_2024['employment']
).round()

# Calculate weekly wage
state_industry_2024['avg_weekly_wage'] = (
    state_industry_2024['avg_annual_pay'] / 52
).round()

print("Shape:", state_industry_2024.shape)

# Alabama only
print(
    state_industry_2024[
        state_industry_2024['area_fips'] == '01000'
    ].to_string(index=False)
)

Shape: (1102, 8)
area_fips  year industry_code  establishments  employment  total_wages  avg_annual_pay  avg_weekly_wage
    01000  2024            11            1555       11484    643735263         56055.0           1078.0
    01000  2024            21             368        6038    637202834        105532.0           2029.0
    01000  2024            22             829       22060   2532747886        114812.0           2208.0
    01000  2024            23           12670      106835   7816543898         73165.0           1407.0
    01000  2024         31-33            7075      285185  21009683277         73670.0           1417.0
    01000  2024            42           10290       79715   6994420873         87743.0           1687.0
    01000  2024         44-45           19583      241389   8949296992         37074.0            713.0
    01000  2024         48-49            5556       89188   5195412954         58252.0           1120.0
    01000  2024            51            5061       23564   1974776305         83805.0           1612.0
    01000  2024            52            9830       75323   7296505824         96870.0           1863.0
    01000  2024            53            6695       26541   1626094076         61267.0           1178.0
    01000  2024            54           20848      128624  12894919359        100253.0           1928.0
    01000  2024            55            1016       17214   2073507492        120455.0           2316.0
    01000  2024            56            9586      121371   5185677292         42726.0            822.0
    01000  2024            61            3739      172021   9721388860         56513.0           1087.0
    01000  2024            62           20979      300538  18756458893         62410.0           1200.0
    01000  2024            71            1727       27190    796293375         29286.0            563.0
    01000  2024            72           11507      188798   4429096775         23459.0            451.0
    01000  2024            81            9795       50878   2654047558         52165.0           1003.0
    01000  2024            92            2149      130027   9364669124         72021.0           1385.0
    01000  2024            99              29          54      3510901         65017.0           1250.0

In [8]:
# Sum employment across all Alabama industry sectors
alabama_sector_total = state_industry_2024.loc[
    state_industry_2024['area_fips'] == '01000',
    'employment'
].sum()

# Official QCEW Total Covered Employment for Alabama
alabama_official_total = qcew.loc[
    (qcew['area_fips'] == '01000') &
    (qcew['own_code'] == 0) &
    (qcew['industry_code'] == '10'),
    'annual_avg_emplvl'
].iloc[0]

print("Sum of industry sectors :", alabama_sector_total)
print("Official total covered  :", alabama_official_total)
print("Difference              :", alabama_sector_total - alabama_official_total)
print(
    "Difference %            :",
    round(
        (alabama_sector_total - alabama_official_total)
        / alabama_official_total * 100,
        4
    )
)

Sum of industry sectors : 2104037
Official total covered  : 2105674
Difference              : -1637
Difference %            : -0.0777

In [9]:
# Total employment obtained from our industry-sector dataset
sector_totals = (
    state_industry_2024
    .groupby('area_fips', as_index=False)
    .agg(sector_employment=('employment', 'sum'))
)

# Official QCEW Total Covered Employment
official_totals = qcew[
    (qcew['agglvl_code'] == 50) &
    (qcew['own_code'] == 0) &
    (qcew['industry_code'] == '10')
][
    ['area_fips', 'annual_avg_emplvl']
].copy()

official_totals = official_totals.rename(
    columns={'annual_avg_emplvl': 'official_employment'}
)

# Compare
validation = sector_totals.merge(
    official_totals,
    on='area_fips',
    how='inner'
)

validation['difference'] = (
    validation['sector_employment']
    - validation['official_employment']
)

validation['difference_pct'] = (
    validation['difference']
    / validation['official_employment']
    * 100
)

print(validation.to_string(index=False))

print("\nMaximum absolute difference %:")
print(validation['difference_pct'].abs().max())

print("\nAverage absolute difference %:")
print(validation['difference_pct'].abs().mean())

area_fips  sector_employment  official_employment  difference  difference_pct
    01000            2104037              2105674       -1637       -0.077742
    02000             329160               329164          -4       -0.001215
    04000            3221639              3222450        -811       -0.025167
    05000            1295579              1295577           2        0.000154
    06000           18183696             18183696           0        0.000000
    08000            2897903              2897901           2        0.000069
    09000            1638355              1683378      -45023       -2.674563
    10000             450211               477336      -27125       -5.682580
    11000             744996               759666      -14670       -1.931112
    12000            9836492              9836491           1        0.000010
    13000            4862002              4862001           1        0.000021
    15000             613832               639801      -25969       -4.058918
    16000             849098               858504       -9406       -1.095627
    17000            5951002              6043357      -92355       -1.528207
    18000            3179541              3179542          -1       -0.000031
    19000            1558826              1562561       -3735       -0.239031
    20000            1429357              1429358          -1       -0.000070
    21000            1986054              1988347       -2293       -0.115322
    22000            1911413              1920359       -8946       -0.465850
    23000             639359               648874       -9515       -1.466386
    24000            2756482              2768546      -12064       -0.435752
    25000            3624641              3644805      -20164       -0.553226
    26000            4407232              4407319         -87       -0.001974
    27000            2932411              2932411           0        0.000000
    28000            1167716              1167716           0        0.000000
    29000            2898176              2898179          -3       -0.000104
    30000             512771               512774          -3       -0.000585
    31000            1018759              1018759           0        0.000000
    32000            1551424              1551426          -2       -0.000129
    33000             685828               687990       -2162       -0.314249
    34000            4252231              4252229           2        0.000047
    35000             869984               869987          -3       -0.000345
    36000            9677098              9705821      -28723       -0.295936
    37000            4901211              4901211           0        0.000000
    38000             428694               428692           2        0.000467
    39000            5520659              5520656           3        0.000054
    40000            1692140              1692477        -337       -0.019912
    41000            1994075              1994161         -86       -0.004313
    42000            6004175              6019836      -15661       -0.260157
    44000             472518               495179      -22661       -4.576325
    45000            2278866              2284611       -5745       -0.251465
    46000             451422               458558       -7136       -1.556183
    47000            3270771              3270771           0        0.000000
    48000           13936120             13936364        -244       -0.001751
    49000            1714013              1714013           0        0.000000
    50000             298084               309138      -11054       -3.575749
    51000            4106143              4106139           4        0.000097
    53000            3593526              3594439        -913       -0.025400
    54000             695662               695658           4        0.000575
    55000            2943651              2944347        -696       -0.023639
    56000             273519               282194       -8675       -3.074126
    72000             947909               947908           1        0.000105
    78000              35560                35639         -79       -0.221667

Maximum absolute difference %:
5.682579985586673

Average absolute difference %:
0.6520076782568992

In [10]:
# Delaware: inspect State × NAICS sector records
de = qcew[
    (qcew['area_fips'] == '10000') &
    (qcew['agglvl_code'] == 54) &
    (qcew['own_code'].isin([1, 2, 3, 5]))
][
    [
        'own_code',
        'industry_code',
        'disclosure_code',
        'annual_avg_emplvl',
        'total_annual_wages'
    ]
].copy()

print(de.to_string(index=False))

print("\nDisclosure code counts:")
print(de['disclosure_code'].value_counts(dropna=False))

 own_code industry_code disclosure_code  annual_avg_emplvl  total_annual_wages
        1         31-33             NaN                  1              114235
        1         44-45             NaN                  5              153796
        1         48-49             NaN               2119           148935310
        1            51             NaN                  0               98117
        1            52             NaN                 78            10611592
        1            54             NaN                 20             2286439
        1            56             NaN                  2               22249
        1            61             NaN                  1               86501
        1            62             NaN               1464           160805358
        1            71             NaN                 47             2427498
        1            72             NaN                 35             1266597
        1            81             NaN                  4              495185
        1            92             NaN               2948           307174186
        2            23             NaN               1481            71871782
        2         48-49               N                  0                   0
        2            51               N                  0                   0
        2            53               N                  0                   0
        2            54               N                  0                   0
        2            56               N                  0                   0
        2            61             NaN              11446          1017917021
        2            62             NaN               3234           187193895
        2            92             NaN              11819           849592271
        3            22               N                  0                   0
        3            53               N                  0                   0
        3            61               N                  0                   0
        3            62               N                  0                   0
        3            81               N                  0                   0
        3            92             NaN               7108           446894609
        5            11               N                  0                   0
        5            21               N                  0                   0
        5            22             NaN               2131           288887941
        5            23             NaN              24283          1883375825
        5         31-33             NaN              26676          2049024912
        5            42             NaN              12775          1256391145
        5         44-45             NaN              51184          2025925414
        5         48-49             NaN              22600          1207568784
        5            51             NaN               3529           367747779
        5            52             NaN              43784          5670792556
        5            53             NaN               6014           432285256
        5            54             NaN              28841          3626385033
        5            55             NaN               7735          1283415955
        5            56             NaN              28768          1646986831
        5            61             NaN               4950           278483548
        5            62             NaN              78754          5532077488
        5            71             NaN               9913           295043982
        5            72             NaN              43751          1183828716
        5            81             NaN              12711           608380552

Disclosure code counts:
disclosure_code
NaN    35
N      12
Name: count, dtype: int64

In [11]:
sector_2024 = qcew[
    (qcew['agglvl_code'] == 54) &
    (qcew['own_code'].isin([1, 2, 3, 5]))
].copy()

# Flag suppressed ownership-industry observations
sector_2024['is_suppressed'] = (
    sector_2024['disclosure_code'] == 'N'
)

state_industry_2024 = (
    sector_2024
    .groupby(
        ['area_fips', 'year', 'industry_code'],
        as_index=False
    )
    .agg(
        establishments=('annual_avg_estabs', 'sum'),
        employment=('annual_avg_emplvl', 'sum'),
        total_wages=('total_annual_wages', 'sum'),
        has_suppressed_data=('is_suppressed', 'max')
    )
)

state_industry_2024['avg_annual_pay'] = (
    state_industry_2024['total_wages']
    / state_industry_2024['employment']
).round()

state_industry_2024['avg_weekly_wage'] = (
    state_industry_2024['avg_annual_pay'] / 52
).round()

state_industry_2024.head()

,area_fips,year,industry_code,establishments,employment,total_wages,has_suppressed_data,avg_annual_pay,avg_weekly_wage
0,01000,2024,11,1555,11484,643735263,False,56055.0,1078.0
1,01000,2024,21,368,6038,637202834,False,105532.0,2029.0
2,01000,2024,22,829,22060,2532747886,False,114812.0,2208.0
3,01000,2024,23,12670,106835,7816543898,True,73165.0,1407.0
4,01000,2024,31-33,7075,285185,21009683277,True,73670.0,1417.0

In [12]:
import pandas as pd
import numpy as np

years = range(2015, 2026)

all_state_totals = []
all_state_industry = []

for year in years:
    
    print(f"Processing {year}...")
    
    url = (
        f"https://data.bls.gov/cew/data/files/"
        f"{year}/csv/{year}_annual_singlefile.zip"
    )
    
    df = pd.read_csv(
        url,
        compression="zip",
        low_memory=False,
        dtype={
            "area_fips": str,
            "industry_code": str
        }
    )

    # -----------------------------------
    # 1. OFFICIAL STATE TOTALS
    # -----------------------------------
    
    state_totals = df[
        (df["agglvl_code"] == 50) &
        (df["own_code"] == 0) &
        (df["industry_code"] == "10")
    ].copy()

    state_totals = state_totals[
        [
            "area_fips",
            "year",
            "annual_avg_estabs",
            "annual_avg_emplvl",
            "total_annual_wages",
            "annual_avg_wkly_wage",
            "avg_annual_pay",
            "oty_annual_avg_emplvl_chg",
            "oty_annual_avg_emplvl_pct_chg",
            "oty_total_annual_wages_chg",
            "oty_total_annual_wages_pct_chg",
            "oty_avg_annual_pay_chg",
            "oty_avg_annual_pay_pct_chg"
        ]
    ]

    state_totals = state_totals.rename(
        columns={
            "annual_avg_estabs": "establishments",
            "annual_avg_emplvl": "employment",
            "total_annual_wages": "total_wages",
            "annual_avg_wkly_wage": "avg_weekly_wage"
        }
    )

    all_state_totals.append(state_totals)

    # -----------------------------------
    # 2. STATE × NAICS SECTOR
    # -----------------------------------

    sector = df[
        (df["agglvl_code"] == 54) &
        (df["own_code"].isin([1, 2, 3, 5]))
    ].copy()

    sector["is_suppressed"] = (
        sector["disclosure_code"] == "N"
    )

    state_industry = (
        sector
        .groupby(
            ["area_fips", "year", "industry_code"],
            as_index=False
        )
        .agg(
            establishments=("annual_avg_estabs", "sum"),
            employment=("annual_avg_emplvl", "sum"),
            total_wages=("total_annual_wages", "sum"),
            has_suppressed_data=("is_suppressed", "max")
        )
    )

    # Recalculate wage metrics
    state_industry["avg_annual_pay"] = np.where(
        state_industry["employment"] > 0,
        state_industry["total_wages"]
        / state_industry["employment"],
        np.nan
    )

    state_industry["avg_weekly_wage"] = (
        state_industry["avg_annual_pay"] / 52
    )

    state_industry["avg_annual_pay"] = (
        state_industry["avg_annual_pay"].round()
    )

    state_industry["avg_weekly_wage"] = (
        state_industry["avg_weekly_wage"].round()
    )

    all_state_industry.append(state_industry)

    print(
        f"  State totals: {len(state_totals):,} | "
        f"Industry rows: {len(state_industry):,}"
    )


# =======================================
# COMBINE ALL YEARS
# =======================================

state_totals = pd.concat(
    all_state_totals,
    ignore_index=True
)

state_industry = pd.concat(
    all_state_industry,
    ignore_index=True
)


print("\nDONE")
print("State totals shape:", state_totals.shape)
print("State × Industry shape:", state_industry.shape)

print("\nYears:")
print(state_totals["year"].value_counts().sort_index())

Processing 2015...
  State totals: 53 | Industry rows: 1,095
Processing 2016...
  State totals: 53 | Industry rows: 1,094
Processing 2017...
  State totals: 53 | Industry rows: 1,093
Processing 2018...
  State totals: 53 | Industry rows: 1,098
Processing 2019...
  State totals: 53 | Industry rows: 1,096
Processing 2020...
  State totals: 53 | Industry rows: 1,095
Processing 2021...
  State totals: 53 | Industry rows: 1,101
Processing 2022...
  State totals: 53 | Industry rows: 1,104
Processing 2023...
  State totals: 53 | Industry rows: 1,107
Processing 2024...
  State totals: 53 | Industry rows: 1,102
Processing 2025...
  State totals: 53 | Industry rows: 1,103

DONE
State totals shape: (583, 13)
State × Industry shape: (12088, 9)

Years:
year
2015    53
2016    53
2017    53
2018    53
2019    53
2020    53
2021    53
2022    53
2023    53
2024    53
2025    53
Name: count, dtype: int64

In [13]:
# ==========================================
# QCEW QUALITY CONTROL
# ==========================================

print("=== 1. STATE CODES ===")

state_codes = sorted(
    state_totals["area_fips"].unique()
)

print(state_codes)
print("Number of areas:", len(state_codes))


print("\n=== 2. DUPLICATES ===")

total_duplicates = state_totals.duplicated(
    subset=["area_fips", "year"]
).sum()

industry_duplicates = state_industry.duplicated(
    subset=["area_fips", "year", "industry_code"]
).sum()

print("State total duplicates:", total_duplicates)
print("State-industry duplicates:", industry_duplicates)


print("\n=== 3. MISSING VALUES ===")

print("\nState totals:")
print(state_totals.isna().sum())

print("\nState × Industry:")
print(state_industry.isna().sum())


print("\n=== 4. INDUSTRY CODES BY YEAR ===")

for year in range(2015, 2026):

    codes = sorted(
        state_industry.loc[
            state_industry["year"] == year,
            "industry_code"
        ].unique()
    )

    print(year, codes)


print("\n=== 5. SUPPRESSION ===")

suppression = (
    state_industry
    .groupby("year")["has_suppressed_data"]
    .agg(["sum", "count"])
)

suppression["pct"] = (
    suppression["sum"]
    / suppression["count"]
    * 100
)

print(suppression)


print("\n=== 6. EMPLOYMENT SANITY CHECK ===")

print(
    state_totals[
        ["employment", "avg_annual_pay", "avg_weekly_wage"]
    ].describe()
)

=== 1. STATE CODES ===
['01000', '02000', '04000', '05000', '06000', '08000', '09000', '10000', '11000', '12000', '13000', '15000', '16000', '17000', '18000', '19000', '20000', '21000', '22000', '23000', '24000', '25000', '26000', '27000', '28000', '29000', '30000', '31000', '32000', '33000', '34000', '35000', '36000', '37000', '38000', '39000', '40000', '41000', '42000', '44000', '45000', '46000', '47000', '48000', '49000', '50000', '51000', '53000', '54000', '55000', '56000', '72000', '78000']
Number of areas: 53

=== 2. DUPLICATES ===
State total duplicates: 0
State-industry duplicates: 0

=== 3. MISSING VALUES ===

State totals:
area_fips                         0
year                              0
establishments                    0
employment                        0
total_wages                       0
avg_weekly_wage                   0
avg_annual_pay                    0
oty_annual_avg_emplvl_chg         0
oty_annual_avg_emplvl_pct_chg     0
oty_total_annual_wages_chg        0
oty_total_annual_wages_pct_chg    0
oty_avg_annual_pay_chg            0
oty_avg_annual_pay_pct_chg        0
dtype: int64

State × Industry:
area_fips                0
year                     0
industry_code            0
establishments           0
employment               0
total_wages              0
has_suppressed_data      0
avg_annual_pay         165
avg_weekly_wage        165
dtype: int64

=== 4. INDUSTRY CODES BY YEAR ===
2015 ['11', '21', '22', '23', '31-33', '42', '44-45', '48-49', '51', '52', '53', '54', '55', '56', '61', '62', '71', '72', '81', '92', '99']
2016 ['11', '21', '22', '23', '31-33', '42', '44-45', '48-49', '51', '52', '53', '54', '55', '56', '61', '62', '71', '72', '81', '92', '99']
2017 ['11', '21', '22', '23', '31-33', '42', '44-45', '48-49', '51', '52', '53', '54', '55', '56', '61', '62', '71', '72', '81', '92', '99']
2018 ['11', '21', '22', '23', '31-33', '42', '44-45', '48-49', '51', '52', '53', '54', '55', '56', '61', '62', '71', '72', '81', '92', '99']
2019 ['11', '21', '22', '23', '31-33', '42', '44-45', '48-49', '51', '52', '53', '54', '55', '56', '61', '62', '71', '72', '81', '92', '99']
2020 ['11', '21', '22', '23', '31-33', '42', '44-45', '48-49', '51', '52', '53', '54', '55', '56', '61', '62', '71', '72', '81', '92', '99']
2021 ['11', '21', '22', '23', '31-33', '42', '44-45', '48-49', '51', '52', '53', '54', '55', '56', '61', '62', '71', '72', '81', '92', '99']
2022 ['11', '21', '22', '23', '31-33', '42', '44-45', '48-49', '51', '52', '53', '54', '55', '56', '61', '62', '71', '72', '81', '92', '99']
2023 ['11', '21', '22', '23', '31-33', '42', '44-45', '48-49', '51', '52', '53', '54', '55', '56', '61', '62', '71', '72', '81', '92', '99']
2024 ['11', '21', '22', '23', '31-33', '42', '44-45', '48-49', '51', '52', '53', '54', '55', '56', '61', '62', '71', '72', '81', '92', '99']
2025 ['11', '21', '22', '23', '31-33', '42', '44-45', '48-49', '51', '52', '53', '54', '55', '56', '61', '62', '71', '72', '81', '92', '99']

=== 5. SUPPRESSION ===
      sum  count        pct
year
2015  417   1095  38.082192
2016  408   1094  37.294333
2017  419   1093  38.334858
2018  425   1098  38.706740
2019  425   1096  38.777372
2020  423   1095  38.630137
2021  424   1101  38.510445
2022  191   1104  17.300725
2023  187   1107  16.892502
2024  210   1102  19.056261
2025  366   1103  33.182230

=== 6. EMPLOYMENT SANITY CHECK ===
         employment  avg_annual_pay  avg_weekly_wage
count  5.830000e+02      583.000000       583.000000
mean   2.789865e+06    59054.596913      1135.679245
std    3.192914e+06    14138.072083       271.894521
min    3.387900e+04    27415.000000       527.000000
25%    7.163230e+05    49090.500000       944.000000
50%    1.836208e+06    56814.000000      1093.000000
75%    3.433589e+06    66044.500000      1270.500000
max    1.821024e+07   128901.000000      2479.000000

In [14]:
# ==========================================
# FINAL QCEW CLEANING
# ==========================================

# Remove Puerto Rico and U.S. Virgin Islands
exclude_territories = ["72000", "78000"]

state_totals = state_totals[
    ~state_totals["area_fips"].isin(exclude_territories)
].copy()

state_industry = state_industry[
    ~state_industry["area_fips"].isin(exclude_territories)
].copy()


# ------------------------------------------
# STATE NAMES
# ------------------------------------------

state_names = {
    "01000": "Alabama",
    "02000": "Alaska",
    "04000": "Arizona",
    "05000": "Arkansas",
    "06000": "California",
    "08000": "Colorado",
    "09000": "Connecticut",
    "10000": "Delaware",
    "11000": "District of Columbia",
    "12000": "Florida",
    "13000": "Georgia",
    "15000": "Hawaii",
    "16000": "Idaho",
    "17000": "Illinois",
    "18000": "Indiana",
    "19000": "Iowa",
    "20000": "Kansas",
    "21000": "Kentucky",
    "22000": "Louisiana",
    "23000": "Maine",
    "24000": "Maryland",
    "25000": "Massachusetts",
    "26000": "Michigan",
    "27000": "Minnesota",
    "28000": "Mississippi",
    "29000": "Missouri",
    "30000": "Montana",
    "31000": "Nebraska",
    "32000": "Nevada",
    "33000": "New Hampshire",
    "34000": "New Jersey",
    "35000": "New Mexico",
    "36000": "New York",
    "37000": "North Carolina",
    "38000": "North Dakota",
    "39000": "Ohio",
    "40000": "Oklahoma",
    "41000": "Oregon",
    "42000": "Pennsylvania",
    "44000": "Rhode Island",
    "45000": "South Carolina",
    "46000": "South Dakota",
    "47000": "Tennessee",
    "48000": "Texas",
    "49000": "Utah",
    "50000": "Vermont",
    "51000": "Virginia",
    "53000": "Washington",
    "54000": "West Virginia",
    "55000": "Wisconsin",
    "56000": "Wyoming"
}


# ------------------------------------------
# NAICS SECTOR NAMES
# ------------------------------------------

industry_names = {
    "11": "Agriculture, Forestry, Fishing and Hunting",
    "21": "Mining, Quarrying, and Oil and Gas Extraction",
    "22": "Utilities",
    "23": "Construction",
    "31-33": "Manufacturing",
    "42": "Wholesale Trade",
    "44-45": "Retail Trade",
    "48-49": "Transportation and Warehousing",
    "51": "Information",
    "52": "Finance and Insurance",
    "53": "Real Estate and Rental and Leasing",
    "54": "Professional, Scientific, and Technical Services",
    "55": "Management of Companies and Enterprises",
    "56": "Administrative and Support and Waste Management and Remediation Services",
    "61": "Educational Services",
    "62": "Health Care and Social Assistance",
    "71": "Arts, Entertainment, and Recreation",
    "72": "Accommodation and Food Services",
    "81": "Other Services (except Public Administration)",
    "92": "Public Administration",
    "99": "Unclassified"
}


# Add state names
state_totals["state"] = (
    state_totals["area_fips"].map(state_names)
)

state_industry["state"] = (
    state_industry["area_fips"].map(state_names)
)

# Add industry names
state_industry["industry"] = (
    state_industry["industry_code"].map(industry_names)
)


# ------------------------------------------
# ORDER COLUMNS
# ------------------------------------------

state_totals = state_totals[
    [
        "year",
        "area_fips",
        "state",
        "employment",
        "establishments",
        "total_wages",
        "avg_annual_pay",
        "avg_weekly_wage",
        "oty_annual_avg_emplvl_chg",
        "oty_annual_avg_emplvl_pct_chg",
        "oty_total_annual_wages_chg",
        "oty_total_annual_wages_pct_chg",
        "oty_avg_annual_pay_chg",
        "oty_avg_annual_pay_pct_chg"
    ]
]

state_industry = state_industry[
    [
        "year",
        "area_fips",
        "state",
        "industry_code",
        "industry",
        "employment",
        "establishments",
        "total_wages",
        "avg_annual_pay",
        "avg_weekly_wage",
        "has_suppressed_data"
    ]
]


# ------------------------------------------
# FINAL CHECK
# ------------------------------------------

print("State totals:", state_totals.shape)
print("State × Industry:", state_industry.shape)

print("\nStates per year:")
print(
    state_totals.groupby("year")["state"].nunique()
)

print("\nMissing state names:")
print(state_totals["state"].isna().sum())

print("\nMissing industry names:")
print(state_industry["industry"].isna().sum())

State totals: (561, 14)
State × Industry: (11629, 11)

States per year:
year
2015    51
2016    51
2017    51
2018    51
2019    51
2020    51
2021    51
2022    51
2023    51
2024    51
2025    51
Name: state, dtype: int64

Missing state names:
0

Missing industry names:
0

In [15]:
output_path = r"data"

state_totals.to_csv(
    output_path + r"\qcew_state_totals_2015_2025.csv",
    index=False
)

state_industry.to_csv(
    output_path + r"\qcew_state_industry_2015_2025.csv",
    index=False
)

print("Files saved successfully.")

Files saved successfully.